server:
  build: .
  environment:
    - RAILS_ENV=development
    - REDIS_HOST=redis.local
    - REDIS_PORT=6379
  volumes:
    - .:/var/www/app
  links:
    - 'redis:redis.local'
shibconfig:
  image: shibconfig
rproxy:
  build: ./docker/builds/reverse_proxy
  ports:
    - "3000:443"
  links:
    - "server:protected.app"
  volumes_from:
    - shibconfig
redis:
  image: redis
