server:
  build: .
  env_file:
    - webapp.env
    - db.env
  volumes:
    - .:/var/www/app
  links:
    - 'db:db.local'
    - 'redis:redis.local'
db:
  build: ./docker/builds/db
  env_file:
    - db.env
  ports:
    - "2222:22"
redis:
  image: redis
shibconfig:
  image: shibconfig
rproxy:
  build: ./docker/builds/reverse_proxy
  ports:
    - "3000:443"
  links:
    - "server:protected.app"
  volumes_from:
    - shibconfig
