ua_test:
  adapter: oracle_enhanced
  host: <%= ENV['UATEST_DB_HOST'] %>
  port: <%= ENV[' UATEST_DB_PORT'] %>
  database: <%= ENV['UATEST_DB_DB'] %>
  username: <%= ENV['UATEST_DB_USER'] %>
  password: <%= ENV['UATEST_DB_PASS'] %>

development:
  adapter: oracle_enhanced
  host: <%= ENV['DEV_DB_HOST'] %>
  port: <%= ENV[' DEV_DB_PORT'] %>
  database: <%= ENV['DEV_DB_DB'] %>
  username: <%= ENV['DEV_DB_USER'] %>
  password: <%= ENV['DEV_DB_PASS'] %>

test:
  adapter: oracle_enhanced
  host: <%= ENV['TEST_DB_HOST'] %>
  port: <%= ENV[' TEST_DB_PORT'] %>
  database: <%= ENV['TEST_DB_DB'] %>
  username: <%= ENV['TEST_DB_USER'] %>
  password: <%= ENV['TEST_DB_PASS'] %>

production:
  adapter: oracle_enhanced
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV[' DB_PORT'] %>
  database: <%= ENV['DB_DB'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
